apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-reader-daemonset
spec:
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool
          command: ["sh", "-c", "tail -f /var/log/syslog"]
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
          - name: varlog
            mountPath: /var/log/syslog
            readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/syslog
